### ISSUE TITLE
Evaluate.py bug

### ISSUE THREAD

**Issue by y0shK** [tgelmi-candusso/urbanwildlife_cv4e#3]
I'm able to run train.py on the cluster using 3 images in the crops folder (one for train, one for validation, and one for test) with no issues. Today, I tried running evaluate.py and received some error messages. I tried troubleshooting by changing the number of classes in categories.csv to just "0,empty and 1,coyote" and changing num_classes in the cfg.yaml file, but this gave me a couple other errors. @maxogden I've attached a log file detailing what I tried and what errors I received if you want to take a look
[evaluate.py.log](https://github.com/tgelmi-candusso/urbanwildlife_cv4e/files/9832758/evaluate.py.log)

**Comment by max-mapper** [comment]
Yes that looks like the same errors I was getting yesterday (ValueError:
The number of FixedLocator locations...)
